#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential', '1.4.0'
cookbook 'mysql',           '3.0.4'
cookbook 'git',             '2.6.0'
cookbook 'zsh',             '1.0.0'
cookbook 'chruby',          git: 'https://github.com/mylesmegyesi/chef-chruby', ref: 'patch-1'
